### ISSUE TITLE
【6.9】飞腾 GMAC 驱动 phytmac_validate() 函数依赖已移除的 .validate() 方式

### ISSUE THREAD

**Issue by MingcongBai** [deepin-community/kernel-rolling#4]
针对 6.9 修缮代码后，发现 `drivers/net/ethernet/phytium/phytmac_main.c` 文件中依然在使用上游已经移除的方式且 `phytmac_validate()` 需适配后续引入的 `.mac_get_caps()` 方式

详见：

- [net: phylink: remove .validate() method](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=da5f6b80ad6417f7cf50d273c1c0ecb885e511e8)
- [net: phylink: provide mac_get_caps() method](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=b6f9774719e5601b32f47021b40fee446b356490)

**Comment by MingcongBai** [comment]
目前已通过回滚移除 `.validate()` 方式的方式使相关代码成功编译，但后续仍需进行适配

cc @Avenger-285714 @opsiff

**Comment by opsiff** [comment]
acked

**Comment by opsiff** [comment]
不好修改 需要根据链接中类似的提交先进行转换
https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/log/?h=v6.1.96&id=6d386f6613269f53b9d21664e582d22e8cda7505

**Comment by MingcongBai** [comment]
已通过 https://github.com/deepin-community/kernel-rolling/pull/7 解决，感谢 @opsiff
